### ISSUE TITLE
bibliography

### ISSUE THREAD

**Issue by norlab** [OpenDataLiteracy/OpenDataAlliance-LD#1]
I noticed that as part of your work you are doing some background reading. I'd love to see the list of readings as they may be helpful for future interns. Could you create a list of readings for this repo (any format is fine)?

**Comment by ghost** [comment]
Perfect. I started one already so it would not be a problem to clean it up and post it up here.

**Comment by ghost** [comment]
Alright I've uploaded a current version. It will be continuously updated as the project goes on.
